# Generated by Django 5.2 on 2025-06-12 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Age', models.IntegerField()),
                ('BusinessTravel', models.CharField(choices=[('Travel_Rarely', 'Travel_Rarely'), ('Travel_Frequently', 'Travel_Frequently'), ('Non-Travel', 'Non-Travel')], default='Travel_Rarely', max_length=50)),
                ('DailyRate', models.IntegerField()),
                ('Department', models.CharField(choices=[('Sales', 'Sales'), ('Research & Development', 'Research & Development'), ('Human Resources', 'Human Resources')], default='Sales', max_length=50)),
                ('DistanceFromHome', models.IntegerField(default=10)),
                ('Education', models.IntegerField(choices=[(1, 'Below College'), (2, 'College'), (3, 'Bachelor'), (4, 'Master'), (5, 'Doctor')], default=3)),
                ('EducationField', models.CharField(choices=[('Life Sciences', 'Life Sciences'), ('Medical', 'Medical'), ('Marketing', 'Marketing'), ('Technical Degree', 'Technical Degree'), ('Human Resources', 'Human Resources'), ('Other', 'Other')], default='Life Sciences', max_length=50)),
                ('EnvironmentSatisfaction', models.IntegerField(default=4)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10)),
                ('HourlyRate', models.IntegerField(default=93)),
                ('JobInvolvement', models.IntegerField(default=4)),
                ('JobLevel', models.IntegerField()),
                ('JobRole', models.CharField(choices=[('Manufacturing Director', 'Manufacturing Director'), ('Research Scientist', 'Research Scientist'), ('Research Director', 'Research Director'), ('Laboratory Technician', 'Laboratory Technician'), ('Sales Executive', 'Sales Executive'), ('Healthcare Representative', 'Healthcare Representative'), ('Manager', 'Manager'), ('Human Resources', 'Human Resources'), ('Sales Representative', 'Sales Representative')], default='Sales Executive', max_length=50)),
                ('JobSatisfaction', models.IntegerField()),
                ('MaritalStatus', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced')], default='Single', max_length=50)),
                ('MonthlyIncome', models.IntegerField()),
                ('MonthlyRate', models.IntegerField(default=10000)),
                ('NumCompaniesWorked', models.IntegerField()),
                ('OverTime', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10)),
                ('PercentSalaryHike', models.IntegerField()),
                ('PerformanceRating', models.IntegerField()),
                ('RelationshipSatisfaction', models.IntegerField(default=4)),
                ('StockOptionLevel', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3')], default=0)),
                ('TotalWorkingYears', models.IntegerField()),
                ('TrainingTimesLastYear', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')], default=3)),
                ('WorkLifeBalance', models.IntegerField(default=3)),
                ('YearsAtCompany', models.IntegerField()),
                ('YearsInCurrentRole', models.IntegerField()),
                ('YearsSinceLastPromotion', models.IntegerField()),
                ('YearsWithCurrManager', models.IntegerField()),
                ('Attrition', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
